name: Deploy to Google Cloud Platform

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        gcloud auth configure-docker

    - name: Build Docker Image
      run: |
        docker build -t gcr.io/${{ secrets.PROJECT_ID }}/vue-app:${{ github.sha }} .

    - name: Push to Google Container Registry
      run: |
        docker push gcr.io/${{ secrets.PROJECT_ID }}/vue-app:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy vue-app \
          --image gcr.io/${{ secrets.PROJECT_ID }}/vue-app:${{ github.sha }} \
          --platform managed \
          --region asia-southeast1 \
          --allow-unauthenticated